# Generated by Django 6.0.3 for tag persistence contract

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('questions_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Теги вопроса', related_name='questions', to='qa.tag'),
        ),
    ]
