# Generated by Django 6.0.3 on 2026-05-05 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_tag_question_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionEditProposal',
            fields=[
                ('question_edit_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор правки вопроса', primary_key=True, serialize=False)),
                ('question_edit_title_before', models.CharField(help_text='Заголовок вопроса до правок', max_length=300)),
                ('question_edit_body_before', models.TextField(help_text='Текст вопроса до правок')),
                ('question_edit_tags_before', models.JSONField(blank=True, default=list, help_text='Нормализованные теги вопроса до правок')),
                ('question_edit_title_after', models.CharField(help_text='Заголовок вопроса после правок', max_length=300)),
                ('question_edit_body_after', models.TextField(help_text='Текст вопроса после правок')),
                ('question_edit_tags_after', models.JSONField(blank=True, default=list, help_text='Нормализованные теги вопроса после правок')),
                ('question_edit_is_approved', models.BooleanField(blank=True, help_text='Была ли одобрена правка вопроса', null=True)),
                ('question_edit_edited_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания предложенной правки')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Дата и время рассмотрения правки', null=True)),
                ('author', models.ForeignKey(help_text='Автор предложенной правки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_edit_proposals', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(help_text='Вопрос, к которому относится правка', on_delete=django.db.models.deletion.CASCADE, related_name='edit_proposals', to='qa.question')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Кто рассмотрел правку', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_edit_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_edit_proposals',
            },
        ),
        migrations.CreateModel(
            name='QuestionRevision',
            fields=[
                ('revision_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор ревизии вопроса', primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('direct_edit', 'Direct edit'), ('approved_proposal', 'Approved proposal')], help_text='Источник ревизии вопроса', max_length=30)),
                ('title_before', models.CharField(help_text='Заголовок вопроса до применения изменений', max_length=300)),
                ('body_before', models.TextField(help_text='Текст вопроса до применения изменений')),
                ('tags_before', models.JSONField(blank=True, default=list, help_text='Нормализованные теги до применения изменений')),
                ('title_after', models.CharField(help_text='Заголовок вопроса после применения изменений', max_length=300)),
                ('body_after', models.TextField(help_text='Текст вопроса после применения изменений')),
                ('tags_after', models.JSONField(blank=True, default=list, help_text='Нормализованные теги после применения изменений')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания ревизии')),
                ('actor', models.ForeignKey(help_text='Пользователь, инициировавший ревизию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_revisions', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(blank=True, help_text='Предложенная правка, если ревизия возникла из approval flow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='qa.questioneditproposal')),
                ('question', models.ForeignKey(help_text='Вопрос, для которого сохранена ревизия', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='qa.question')),
                ('tags', models.ManyToManyField(blank=True, help_text='Финальный набор тегов после ревизии', related_name='question_revisions', to='qa.tag')),
            ],
            options={
                'db_table': 'question_revisions',
            },
        ),
        migrations.CreateModel(
            name='QuestionEditEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор события жизненного цикла вопроса', primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('direct_edited', 'Direct edited'), ('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected')], help_text='Тип события жизненного цикла вопроса', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания события')),
                ('actor', models.ForeignKey(help_text='Пользователь, вызвавший событие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_edit_events', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(help_text='Вопрос, к которому относится событие', on_delete=django.db.models.deletion.CASCADE, related_name='edit_events', to='qa.question')),
                ('proposal', models.ForeignKey(blank=True, help_text='Связанная предложенная правка вопроса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='qa.questioneditproposal')),
                ('revision', models.ForeignKey(blank=True, help_text='Связанная ревизия вопроса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='qa.questionrevision')),
            ],
            options={
                'db_table': 'question_edit_events',
            },
        ),
        migrations.AddIndex(
            model_name='questioneditproposal',
            index=models.Index(fields=['question', 'question_edit_is_approved'], name='question_ed_questio_1e12f5_idx'),
        ),
        migrations.AddIndex(
            model_name='questioneditproposal',
            index=models.Index(fields=['author'], name='question_ed_author__b1be33_idx'),
        ),
        migrations.AddIndex(
            model_name='questionrevision',
            index=models.Index(fields=['question', 'created_at'], name='question_re_questio_b93c77_idx'),
        ),
        migrations.AddIndex(
            model_name='questionrevision',
            index=models.Index(fields=['source'], name='question_re_source_0d7cba_idx'),
        ),
        migrations.AddIndex(
            model_name='questioneditevent',
            index=models.Index(fields=['question', 'created_at'], name='question_ed_questio_6c45cd_idx'),
        ),
        migrations.AddIndex(
            model_name='questioneditevent',
            index=models.Index(fields=['event_type'], name='question_ed_event_t_dae6c7_idx'),
        ),
    ]
