# Generated by Django 6.0.3 on 2026-05-14 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_questioneditproposal_questionrevision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFavorite',
            fields=[
                ('favorite_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор избранного вопроса', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата добавления вопроса в избранное')),
                ('question', models.ForeignKey(help_text='Вопрос, добавленный в избранное', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='qa.question')),
                ('user', models.ForeignKey(help_text='Пользователь, добавивший вопрос в избранное', on_delete=django.db.models.deletion.CASCADE, related_name='question_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_favorites',
                'indexes': [models.Index(fields=['user', 'created_at'], name='question_fa_user_id_d63a5f_idx'), models.Index(fields=['question'], name='question_fa_questio_c1cdca_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_question_favorite_user_question')],
            },
        ),
    ]
