FROM node:24-alpine AS build

WORKDIR /app

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

COPY ./src/frontend/package*.json ./
RUN npm ci

COPY ./src/frontend ./
RUN npm run build

FROM nginx:stable-alpine

COPY ./docker/nginx.frontend.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
