from decimal import Decimal


AUTHORED_QUESTION = 'authored_question'
POSTED_SOLUTION = 'posted_solution'
BEST_SOLUTION = 'best_solution'
APPROVED_EDIT = 'approved_edit'
QUESTION_UPVOTE = 'question_upvote'
SOLUTION_UPVOTE = 'solution_upvote'

AUTHORED_QUESTION_WEIGHT = Decimal('1.0000')
POSTED_SOLUTION_WEIGHT = Decimal('1.0000')
BEST_SOLUTION_WEIGHT = Decimal('2.0000')
APPROVED_EDIT_WEIGHT = Decimal('0.5000')
QUESTION_UPVOTE_WEIGHT = Decimal('0.2500')
SOLUTION_UPVOTE_WEIGHT = Decimal('0.7500')

CANONICAL_ACTIVITY_WEIGHTS = {
    AUTHORED_QUESTION: AUTHORED_QUESTION_WEIGHT,
    POSTED_SOLUTION: POSTED_SOLUTION_WEIGHT,
    BEST_SOLUTION: BEST_SOLUTION_WEIGHT,
    APPROVED_EDIT: APPROVED_EDIT_WEIGHT,
    QUESTION_UPVOTE: QUESTION_UPVOTE_WEIGHT,
    SOLUTION_UPVOTE: SOLUTION_UPVOTE_WEIGHT,
}

POSITIVE_ACTIVITY_TYPES = tuple(CANONICAL_ACTIVITY_WEIGHTS.keys())
