# Generated by Django 6.0.3 on 2026-05-10 17:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qa', '0004_questioneditproposal_questionrevision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(choices=[('tag', 'Tag'), ('manual', 'Manual'), ('provider', 'Provider')], default='tag', max_length=30)),
                ('provider', models.CharField(blank=True, default='', max_length=128)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_concepts',
                'indexes': [models.Index(fields=['slug'], name='knowledge_concept_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConceptTagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('tag', 'Tag'), ('manual', 'Manual'), ('provider', 'Provider')], default='tag', max_length=30)),
                ('provider', models.CharField(blank=True, default='', max_length=128)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_mappings', to='qa.tag')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_mappings', to='knowledge.knowledgeconcept')),
            ],
            options={
                'db_table': 'concept_tag_mappings',
            },
        ),
        migrations.CreateModel(
            name='QuestionConceptEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('tag', 'Tag'), ('manual', 'Manual'), ('provider', 'Provider')], default='tag', max_length=30)),
                ('provider', models.CharField(blank=True, default='', max_length=128)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_edges', to='knowledge.knowledgeconcept')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_edges', to='qa.question')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_concept_edges', to='qa.tag')),
                ('tag_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_edges', to='knowledge.concepttagmapping')),
            ],
            options={
                'db_table': 'question_concept_edges',
            },
        ),
        migrations.AddIndex(
            model_name='concepttagmapping',
            index=models.Index(fields=['tag', 'concept'], name='kmap_tag_concept_idx'),
        ),
        migrations.AddIndex(
            model_name='concepttagmapping',
            index=models.Index(fields=['concept'], name='concept_mapping_concept_idx'),
        ),
        migrations.AddConstraint(
            model_name='concepttagmapping',
            constraint=models.UniqueConstraint(fields=('tag', 'concept'), name='unique_concept_tag_mapping'),
        ),
        migrations.AddIndex(
            model_name='questionconceptedge',
            index=models.Index(fields=['question', 'concept'], name='qedge_question_concept_idx'),
        ),
        migrations.AddIndex(
            model_name='questionconceptedge',
            index=models.Index(fields=['concept'], name='question_edge_concept_idx'),
        ),
        migrations.AddIndex(
            model_name='questionconceptedge',
            index=models.Index(fields=['tag'], name='question_edge_tag_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionconceptedge',
            constraint=models.UniqueConstraint(fields=('question', 'concept'), name='unique_question_concept_edge'),
        ),
    ]
