# Generated by Django 6.0.3 on 2026-05-10 18:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('knowledge', '0001_initial'),
        ('qa', '0004_questioneditproposal_questionrevision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConceptActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('authored_question', 'Authored question'), ('posted_solution', 'Posted solution'), ('best_solution', 'Best solution'), ('approved_edit', 'Approved edit'), ('question_upvote', 'Question upvote'), ('solution_upvote', 'Solution upvote')], max_length=40)),
                ('weight_delta', models.DecimalField(decimal_places=4, max_digits=8)),
                ('source', models.CharField(choices=[('question', 'Question'), ('solution', 'Solution'), ('best_solution', 'Best solution'), ('approved_edit', 'Approved edit'), ('reputation_transaction', 'Reputation transaction'), ('rebuild', 'Rebuild')], max_length=40)),
                ('provider', models.CharField(blank=True, default='', max_length=128)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('source_object_id', models.UUIDField()),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_activities', to='knowledge.knowledgeconcept')),
                ('related_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_concept_activities', to='qa.question')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_concept_activities',
                'indexes': [models.Index(fields=['user', 'concept'], name='ucact_user_concept_idx'), models.Index(fields=['user', 'activity_type'], name='ucact_user_type_idx'), models.Index(fields=['concept', 'activity_type'], name='ucact_concept_type_idx'), models.Index(fields=['source_content_type', 'source_object_id'], name='ucact_source_object_idx')],
            },
        ),
    ]
