# Generated by GSD for M013/S04 graph freshness state

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_user_concept_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKnowledgeGraphState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('stale', 'Stale'), ('rebuilding', 'Rebuilding'), ('failed', 'Failed')], default='fresh', max_length=20)),
                ('stale_reason', models.CharField(blank=True, choices=[('activity_sync_failed', 'Activity sync failed'), ('activity_rebuild_failed', 'Activity rebuild failed'), ('manual_rebuild_requested', 'Manual rebuild requested'), ('unknown', 'Unknown')], default='', max_length=64)),
                ('last_error_message', models.CharField(blank=True, default='', max_length=255)),
                ('last_failed_phase', models.CharField(blank=True, default='', max_length=80)),
                ('last_rebuild_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_rebuild_finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graph_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_knowledge_graph_states',
                'indexes': [models.Index(fields=['user'], name='ukgstate_user_idx'), models.Index(fields=['status'], name='ukgstate_status_idx')],
            },
        ),
    ]
