# Generated by GSD M004 S01 reputation foundation.

import uuid
from django.db import migrations, models
import django.db.models.deletion


DEFAULT_THRESHOLDS = [
    ('newcomer', 0, 'Базовый уровень для новых пользователей'),
    ('participant', 30, 'Пользователь с начальным подтвержденным участием'),
    ('expert', 100, 'Пользователь с устойчивым вкладом'),
    ('master', 300, 'Пользователь с высоким доверием сообщества'),
]


def seed_reputation_thresholds(apps, schema_editor):
    ReputationLevelThreshold = apps.get_model('user', 'ReputationLevelThreshold')
    for level, minimum_score, description in DEFAULT_THRESHOLDS:
        ReputationLevelThreshold.objects.update_or_create(
            level=level,
            defaults={
                'minimum_score': minimum_score,
                'is_active': True,
                'description': description,
            },
        )


def unseed_reputation_thresholds(apps, schema_editor):
    ReputationLevelThreshold = apps.get_model('user', 'ReputationLevelThreshold')
    ReputationLevelThreshold.objects.filter(level__in=[level for level, _, _ in DEFAULT_THRESHOLDS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manual_reputation_level',
            field=models.CharField(blank=True, choices=[('newcomer', 'Новичок'), ('participant', 'Участник'), ('expert', 'Эксперт'), ('master', 'Мастер')], help_text='Ручной уровень репутации, если администратор переопределил расчетный уровень', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='ReputationLevelThreshold',
            fields=[
                ('reputation_level_threshold_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор порога репутации', primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('newcomer', 'Новичок'), ('participant', 'Участник'), ('expert', 'Эксперт'), ('master', 'Мастер')], help_text='Уровень репутации', max_length=32, unique=True)),
                ('minimum_score', models.PositiveIntegerField(help_text='Минимальное количество репутации для уровня')),
                ('is_active', models.BooleanField(default=True, help_text='Используется ли порог при расчете уровня')),
                ('description', models.TextField(blank=True, help_text='Пояснение для администраторов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reputation_level_thresholds',
                'ordering': ['minimum_score'],
            },
        ),
        migrations.AddField(
            model_name='reputationtransaction',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Пользователь или администратор, вызвавший изменение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reputation_transactions', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='reputationtransaction',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Тип объекта-источника изменения репутации', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='reputationtransaction',
            name='object_id',
            field=models.UUIDField(blank=True, help_text='Идентификатор объекта-источника изменения репутации', null=True),
        ),
        migrations.AddField(
            model_name='reputationtransaction',
            name='note',
            field=models.TextField(blank=True, help_text='Пояснение к изменению репутации'),
        ),
        migrations.AddField(
            model_name='reputationtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время изменения репутации', null=True),
        ),
        migrations.AlterField(
            model_name='reputationtransaction',
            name='reputation_transaction_reason',
            field=models.CharField(choices=[('best_solution', 'Best solution'), ('solution_upvoted', 'Solution upvoted'), ('solution_downvoted', 'Solution downvoted'), ('question_upvoted', 'Question upvoted'), ('approved_edit', 'Approved edit'), ('achievement_earned', 'Achievement earned'), ('admin_adjustment', 'Admin adjustment'), ('manual_level_override', 'Manual level override')], help_text='Причина начисления/снятия репутации', max_length=128),
        ),
        migrations.AlterField(
            model_name='reputationtransaction',
            name='user',
            field=models.ForeignKey(help_text='Пользователь транзакции', on_delete=django.db.models.deletion.CASCADE, related_name='reputation_transactions', to='user.customuser'),
        ),
        migrations.AlterModelOptions(
            name='reputationtransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='reputationlevelthreshold',
            index=models.Index(fields=['is_active', 'minimum_score'], name='rep_threshold_active_score_idx'),
        ),
        migrations.AddIndex(
            model_name='reputationtransaction',
            index=models.Index(fields=['user', '-created_at'], name='rep_tx_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='reputationtransaction',
            index=models.Index(fields=['reputation_transaction_reason'], name='rep_tx_reason_idx'),
        ),
        migrations.AddIndex(
            model_name='reputationtransaction',
            index=models.Index(fields=['content_type', 'object_id'], name='rep_tx_source_idx'),
        ),
        migrations.RunPython(seed_reputation_thresholds, unseed_reputation_thresholds),
        migrations.AlterField(
            model_name='reputationtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время изменения репутации'),
        ),
    ]
