# Generated by Django 6.0.3 on 2026-05-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_reputation_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationPolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=32, unique=True)),
                ('protected_newcomer_window_hours', models.PositiveIntegerField(default=12, help_text='Длительность protected-window для вопросов новичков в часах.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reputation policy config',
                'verbose_name_plural': 'Reputation policy config',
                'db_table': 'reputation_policy_config',
            },
        ),
    ]
