# Generated by GSD for stable user avatar cache busting

from django.db import migrations, models
import apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_expert_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_avatar_updated_at',
            field=models.DateTimeField(blank=True, help_text='Дата последнего обновления аватара', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_avatar_url',
            field=models.ImageField(blank=True, help_text='Аватар пользователя', null=True, upload_to=apps.user.models.user_avatar_upload_to),
        ),
    ]
